service: vpc-aurora-sql

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    MYSQL_HOST: ${env:MYSQL_HOST, "serverless-ra.cluster-cn60skwdfw0l.us-east-1.rds.amazonaws.com"}
    MYSQL_PORT: ${env:MYSQL_PORT, "3306"}
    MYSQL_USER: ${env:MYSQL_USER, "regisandrade"}
    MYSQL_PASSWD: ${env:MYSQL_PASS, "regis123789"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "heroes"}
  vpc:
    securityGroupIds:
      - sg-8e29578d
    subnetIds:
      - subnet-6a265435
      - subnet-856061c8
      - subnet-820f7ee4
      - subnet-585f2379
      - subnet-61301b6f
      - subnet-917ffaa0

package:
  excludeDevDependencies: true

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: hello

